training:
  model_name_or_path: bert-base-uncased
  output_dir: data/models/criteria_run
  epochs: 1
  batch_size: 4
  grad_accum_steps: 1
  max_length: 384
  seed: 42
  mixed_precision: bf16
  loss_type: ranknet
  margin: 0.2
  mlflow_run_name: criteria-ranker-demo
data:
  pairwise_path: data/pairs/criteria_train.jsonl
  dev_path: data/pairs/criteria_dev.jsonl
  test_path: data/pairs/criteria_test.jsonl
judge:
  model: gemini-2.5-flash
  rubric_version: clinical_rubric_v1
